baseURL = "https://mercymarkus.com/"
languageCode = "en-us"
title = 'Mercy Markus'
enableRobotsTXT = true
mode = "light" # or "dark" or "auto"

copyright = "Â© Copyright Notice"
enableemoji = true
ignorecache = true
pygmentsUseClasses = true
pygmentsCodefences = true

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[params]
	subtitle = "Fiddling with code ğŸ‘©ğŸ¾â€ğŸ’»"
  images = ["https://res.cloudinary.com/mercymarkus-com/image/upload/v1655643575/MercyMarkus_q4mpjj.png"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 3

  [markup.highlight]
    lineNos = true
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineNoStart = 1
    lineAnchors = 'code-line'
    lineNumbersInTable = true
    noClasses = false
    style = 'monokailight'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Series"
url = "/series"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/MercyMarkus"

# Used to define the twitter card site
[Social]
  twitter = "MercyMarkus"

[[params.social]]
name = "linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/mercymarkus/"

[[params.social]]
name = "twitter"
icon = "twitter"
url = "https://twitter.com/MercyMarkus"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
   series = "series"
